apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: med-erp
  labels:
    app: frontend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend

          image: yashpatel017/docker-frontend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 80
              protocol: TCP

          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"

            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: med-erp

spec:
  selector:
    app: frontend

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: LoadBalancer